version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: digital-ocean
                command: ssh -o StrictHostKeyChecking=no ${host} "cd /var/www/dev.psitdevis.com.br/html/port-for-devis"
            - run:
                name: install
                command: git pull origin master & npm install & npm run start

workflows:
    build-and-test:
      jobs:
        - build-and-test
