version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm build
            - run: echo "workdir ${workdir}"
            - run: echo 'THE FINGERPRINT' >> ~/.ssh/known_hosts
            - deploy:
                name: digital-ocean
                command: ssh -o StrictHostKeyChecking=no ${host} "cd /var/www/dev.psitdevis.com.br/html/port-for-devis"
                - run: git pull
                - run: npm install
                - runs: npm run start
workflows:
    build-and-test:
      jobs:
        - build-and-test
