version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm build
            - deploy:
                name: digital-ocean
                command: ssh -o $host "cd /var/www/dev.psitdevis.com.br/html; git pull; npm install; npm run start"
workflows:
    build-and-test:
      jobs:
        - build-and-test
